name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

env:
  CARGO_TERM_COLOR: always
  # https://github.com/xd009642/tarpaulin
  TARPAULIN_VERSION: 0.35.1
  # https://github.com/est31/cargo-udeps
  UDEPS_VERSION: 0.1.60
  # https://github.com/rustsec/rustsec
  AUDIT_VERSION: 0.22.1

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ${{ matrix.os }}
  
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Cargo fmt and clippy

    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt --all -- --check

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Cargo test and tarpaulin
    needs: linter

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Install cargo-tarpaulin@${{ env.TARPAULIN_VERSION }}
      if: matrix.os == 'ubuntu-latest'
      run: cargo install cargo-tarpaulin@${{ env.TARPAULIN_VERSION }} --locked

    - name: Run tarpaulin
      if: matrix.os == 'ubuntu-latest'
      run: cargo tarpaulin --verbose

  audit:
    runs-on: ubuntu-latest
    name: Cargo udeps and audit
    needs: linter

    steps:
    - uses: actions/checkout@v4

    - name: Install cargo-udeps
      run: cargo install cargo-udeps@${{ env.UDEPS_VERSION }} --locked

    - name: Install cargo-audit
      run: cargo install cargo-audit@${{ env.AUDIT_VERSION }} --locked

    - name: Run cargo udeps
      run: cargo +nightly udeps --verbose

    - name: Run cargo audit
      run: cargo audit
